spring:
  datasource:
    url: jdbc:h2:mem:alura.desafio
    username: user
    password:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: false
        trace: false
